# Generated by Django 6.0 on 2025-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('two_factor_enabled', models.CharField(blank=True, max_length=255, null=True)),
                ('two_factor_method', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_at', models.CharField(blank=True, max_length=255, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('login_count', models.CharField(blank=True, max_length=255, null=True)),
                ('failed_login_attempts', models.CharField(blank=True, max_length=255, null=True)),
                ('password_changed_at', models.CharField(blank=True, max_length=255, null=True)),
                ('password_change_required', models.CharField(blank=True, max_length=255, null=True)),
                ('password_history', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_preferences', models.CharField(blank=True, max_length=255, null=True)),
                ('privacy_settings', models.CharField(blank=True, max_length=255, null=True)),
                ('max_concurrent_sessions', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified_at', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_verified_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
